name: CI
on:
  push:
    branches: [main, master]
    tags: ["*"]
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
          - '1' # automatically expands to the latest stable 1.x release of Julia
          - nightly
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - name: Update /etc/hosts for TLS test
        run: echo "127.0.0.1 redisjltest" | sudo tee -a /etc/hosts
      - name: Start redis server
        run: |
          echo "Starting redis server"
          pwd
          test/conf/redis.sh
          sleep 5
          echo "Redis started"
      - name: Start redis cluster
        run: |
          echo "Starting redis cluster"
          chmod +x test/conf/redis-cluster.sh
          test/conf/redis-cluster.sh
          sleep 10
          echo "Redis cluster started"
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        id: codecov
        continue-on-error: true
        with:
          files: lcov.info
          fail_ci_if_error: false
